#!/bin/bash

if ( ! command -v scrapy ); then
    echo "Please source the environment which installed scrapy"
    exit 1
fi


function run_crawler() {
    scrapy crawl $1 2>&1 | grep ERROR
}

SPIDER=$1
pushd vnw/vnw/spiders/
if [ ! -z $SPIDER ]; then
    run_crawler $SPIDER
else
    for spider in *.py; do
        spider_name=$(basename $spider)
        SPIDER=${spider_name/.py/}
        run_crawler $SPIDER
    done
fi

popd
