#!/bin/bash

if ( ! command -v scrapy ); then
    echo "Please source the environment which installed scrapy"
    exit 1
fi

tmpfile=$(mktemp)

function run_crawler() {
    scrapy crawl $1 2>&1 | tee -a $tmpfile |grep ERROR
}

SPIDER=$1
pushd vnw/vnw/spiders/
if [ ! -z $SPIDER ]; then
    run_crawler $SPIDER
else
    for spider in *.py; do
        spider_name=$(basename $spider)
        SPIDER=${spider_name/.py/}
        run_crawler $SPIDER
    done
fi

popd

if [ "$(wc -l $tmpfile)" == 0 ]; then
    rm -f $tmpfile
    exit 0
else
    rm -f $tmpfile
    exit 1
fi
