#!/bin/bash

if ( ! command -v scrapy >/dev/null ); then
    echo "Please source the environment which installed scrapy"
    exit 1
fi

tmpfile=$(mktemp)

function run_crawler() {
    echo "Crawling $1 spider"
    scrapy crawl $1 2>> $tmpfile.$1
    grep 'KeyError: ' $tmpfile.$1 && exit 1
    grep ERROR: $tmpfile.$1 | tee -a $tmpfile.err || true
}

SPIDER=$1
pushd vnw/vnw/spiders/ >/dev/null
if [ ! -z $SPIDER ]; then
    run_crawler $SPIDER
else
    for spider in *.py; do
        spider_name=$(basename $spider)
        SPIDER=${spider_name/.py/}
        [ $SPIDER == "__init__" ] && continue
        run_crawler $SPIDER
    done
fi

popd >/dev/null

if [ "$(wc -l $tmpfile.err | cut -d' ' -f1)" -eq 0 ]; then
    exit 0
else
    exit 1
fi
